//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peltier_GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Peltier_GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string AutomaticMode_Label {
            get {
                return ResourceManager.GetString("AutomaticMode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Button_Connect {
            get {
                return ResourceManager.GetString("Button_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Button_Disconnect {
            get {
                return ResourceManager.GetString("Button_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM Port.
        /// </summary>
        public static string COMPort_Label_Def {
            get {
                return ResourceManager.GetString("COMPort_Label_Def", resourceCulture);
            }
        }
        
        public static System.Drawing.Icon ConnectedIcon {
            get {
                object obj = ResourceManager.GetObject("ConnectedIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ConnectedImg {
            get {
                object obj = ResourceManager.GetObject("ConnectedImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string ConnectionGroup_Label {
            get {
                return ResourceManager.GetString("ConnectionGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string ControlMode_Label {
            get {
                return ResourceManager.GetString("ControlMode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string ControlTabDef {
            get {
                return ResourceManager.GetString("ControlTabDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string DebugTabDef {
            get {
                return ResourceManager.GetString("DebugTabDef", resourceCulture);
            }
        }
        
        public static System.Drawing.Icon DisconnectedIcon {
            get {
                object obj = ResourceManager.GetObject("DisconnectedIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DisconnectedImg {
            get {
                object obj = ResourceManager.GetObject("DisconnectedImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed.
        /// </summary>
        public static string ElapseTime_Label {
            get {
                return ResourceManager.GetString("ElapseTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Reading the Configuration File.
        /// </summary>
        public static string Error_ReadConfFile {
            get {
                return ResourceManager.GetString("Error_ReadConfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Reading the Language Configuration.
        /// </summary>
        public static string Error_ReadConfLanguage {
            get {
                return ResourceManager.GetString("Error_ReadConfLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peltier Cell Temperature.
        /// </summary>
        public static string Graph_PeltierCurve {
            get {
                return ResourceManager.GetString("Graph_PeltierCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Temperature.
        /// </summary>
        public static string Graph_RoomCurve {
            get {
                return ResourceManager.GetString("Graph_RoomCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature of Peltier Cell System.
        /// </summary>
        public static string GraphTitle_Label {
            get {
                return ResourceManager.GetString("GraphTitle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time [Minutes].
        /// </summary>
        public static string GraphX_Label {
            get {
                return ResourceManager.GetString("GraphX_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T [°C].
        /// </summary>
        public static string GraphY_Label {
            get {
                return ResourceManager.GetString("GraphY_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string ManualMode_Label {
            get {
                return ResourceManager.GetString("ManualMode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Control.
        /// </summary>
        public static string ManualTabDef {
            get {
                return ResourceManager.GetString("ManualTabDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM Options.
        /// </summary>
        public static string MenuItem_COM_Options {
            get {
                return ResourceManager.GetString("MenuItem_COM_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics Options.
        /// </summary>
        public static string MenuItem_Graph_Options {
            get {
                return ResourceManager.GetString("MenuItem_Graph_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID Options.
        /// </summary>
        public static string MenuItem_PID_Options {
            get {
                return ResourceManager.GetString("MenuItem_PID_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuItemExitName {
            get {
                return ResourceManager.GetString("MenuItemExitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuItemFileName {
            get {
                return ResourceManager.GetString("MenuItemFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuItemHelpAbout {
            get {
                return ResourceManager.GetString("MenuItemHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuItemHelpName {
            get {
                return ResourceManager.GetString("MenuItemHelpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string MenuItemOptionsName {
            get {
                return ResourceManager.GetString("MenuItemOptionsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Peltier Cell.
        /// </summary>
        public static string Peltier_Temperature_Label {
            get {
                return ResourceManager.GetString("Peltier_Temperature_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Name.
        /// </summary>
        public static string PortName_Label {
            get {
                return ResourceManager.GetString("PortName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Temperature.
        /// </summary>
        public static string Room_Temperature_Label {
            get {
                return ResourceManager.GetString("Room_Temperature_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string StatusBar_Connected {
            get {
                return ResourceManager.GetString("StatusBar_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconneted.
        /// </summary>
        public static string StatusBar_Disconnected {
            get {
                return ResourceManager.GetString("StatusBar_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string TemperatureGroupBox_Label {
            get {
                return ResourceManager.GetString("TemperatureGroupBox_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Temeperature.
        /// </summary>
        public static string TemperatureGroupBox_Label1 {
            get {
                return ResourceManager.GetString("TemperatureGroupBox_Label1", resourceCulture);
            }
        }
    }
}
